### ISSUE TITLE
RealEditText behaves like RealTextView (Compatibility with Eclipse)

### ISSUE THREAD

**Issue by ViksaaSkool** [marcelpinto/RealTextView#1]
Hi, 
First let me say: great library, I would gladly use this in Android Studio. 
Yet, there is problem, I have project in Eclipse that has the need of the RealEditText view properties. I've tried *manual import of the library and the RealEditText behaves like TextView. 

in my layout.xml: 
<com.hardsoftstudio.real.RealEditText
        android:id="@+id/realEditText1"
        android:layout_width="400dp"
        android:layout_height="300dp"
        android:layout_below="@+id/textView1"
        android:layout_marginTop="70dp"
        android:layout_toRightOf="@+id/textView1"
        android:ems="10"
        real:minTextSize="18sp"
        android:text="RealEditText" >

I also tried adding the property android:editable="true" to the view, but it made no difference. Any ideas why this happens?  

*copied the lib package (without the checkbox and button views), updated the attr.xml with the lib data

**Comment by AndroidDeveloperLB** [comment]
@skimarxall I'm using Android-Studio and also got the same issue with the RealEditText . It doesn't allow the user to edit the text, unless you add those attributes.
Please fix it. By default, EditText should be editable by the user.
