### ISSUE TITLE
Emoji not showing!!!!!!

### ISSUE THREAD

**Issue by kawadkarrocky** [marcelpinto/RealTextView#8]
Hey Boy Hi, I am using RealTextView to support html rendered textview but the problem is the library doesnot showing support to GIF or any other image and neither it is rendering html properties, any help will be appreciatable, thanks.

**Comment by skimarxall** [comment]
The library supports what Android TextView supports. Thus html is limited to some tags and gif or other kind of image formats are not supported either. For this you may use other libraries.
